<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.team4u</groupId>
        <artifactId>team4u-framework</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>team4u-retry</artifactId>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.team4u</groupId>
            <artifactId>team4u-criterion</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.team4u</groupId>
            <artifactId>team4u-proxy</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.team4u</groupId>
            <artifactId>team4u-policy</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.team4u</groupId>
            <artifactId>team4u-config-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.team4u</groupId>
            <artifactId>team4u-bean</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.team4u</groupId>
            <artifactId>team4u-config-test</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- 基础依赖 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- 测试依赖 -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
