CREATE TABLE IF NOT EXISTS lease_task
(
    task_id           VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    queue_name        VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    task_type         VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    payload           TEXT,
    deduplication_key VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    status            VARCHAR(32) NOT NULL,
    priority          INT NOT NULL DEFAULT 0,
    attempt_count     INT NOT NULL DEFAULT 0,
    worker_id         VARCHAR(128),
    lease_token       VARCHAR(128),
    lease_expires_at  BIGINT,
    visible_at        BIGINT NOT NULL,
    created_at        BIGINT NOT NULL,
    updated_at        BIGINT NOT NULL,
    version           BIGINT NOT NULL DEFAULT 0,
    error_message     TEXT,
    attributes_json   TEXT,
    PRIMARY KEY (task_id),
    UNIQUE KEY uk_lease_task_dedup (queue_name, task_type, deduplication_key),
    KEY idx_lease_task_pending (queue_name, status, task_type, visible_at, priority, created_at, task_id),
    KEY idx_lease_task_expired (queue_name, status, task_type, lease_expires_at, priority, created_at, task_id),
    KEY idx_lease_task_query (queue_name, task_type, status, worker_id, created_at, task_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin;
