package com.team4u.framework.flow;

import org.junit.Assert;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * 契约正确性与边界测试：
 * 1. 父子流程与分支 executionId 一致性
 * 2. 挂载子流程与冲突分支节点的 invocationId 唯一性
 * 3. 嵌套 Observer 与 Trace 层级传播
 * 4. Observer Error 传播与非 Error 隔离
 * 5. InterruptedException 恢复后中断状态保留
 * 6. recover/ensure 重新抛出原异常时防止 self-suppression
 *
 * @author jay.wu
 */
public class FlowContractCorrectnessTest {

    static class CustomTestException extends RuntimeException {
        CustomTestException(String message) {
            super(message);
        }
    }

    @Test
    public void parentChildExecutionId_autoGenerated_allStepsShareSameId() {
        List<String> recordedExecIds = new ArrayList<String>();

        Flow<String, String> childFlow = Flows.<String>begin("child")
                .step("child-s1", (ctx, in) -> {
                    recordedExecIds.add(ctx.executionId());
                    return in + "-c1";
                })
                .step("child-s2", (ctx, in) -> {
                    recordedExecIds.add(ctx.executionId());
                    return in + "-c2";
                })
                .build();

        Flow<String, String> branchFlow = Flows.<String>begin("branch")
                .step("branch-s1", (ctx, in) -> {
                    recordedExecIds.add(ctx.executionId());
                    return in + "-b1";
                })
                .build();

        Flow<String, String> parentFlow = Flows.<String>begin("parent")
                .step("parent-s1", (ctx, in) -> {
                    recordedExecIds.add(ctx.executionId());
                    return in + "-p1";
                })
                .then(childFlow)
                .choose("choose-ch", in -> "A")
                .when("A", branchFlow)
                .end()
                .step("parent-s2", (ctx, in) -> {
                    recordedExecIds.add(ctx.executionId());
                    return in + "-p2";
                })
                .build();

        FlowExecution<String> exec = parentFlow.run("init");
        Assert.assertTrue(exec.result().isSucceeded());
        Assert.assertEquals("init-p1-c1-c2-b1-p2", exec.result().value());

        Assert.assertEquals(5, recordedExecIds.size());
        String expectedExecId = exec.executionId();
        Assert.assertNotNull(expectedExecId);
        Assert.assertFalse(expectedExecId.trim().isEmpty());

        for (String execId : recordedExecIds) {
            Assert.assertEquals(expectedExecId, execId);
        }
    }

    @Test
    public void parentChildExecutionId_explicitlySupplied_allStepsShareSameId() {
        List<String> recordedExecIds = new ArrayList<String>();

        Flow<String, String> childFlow = Flows.<String>begin("child")
                .step("child-s1", (ctx, in) -> {
                    recordedExecIds.add(ctx.executionId());
                    return in;
                })
                .build();

        Flow<String, String> parentFlow = Flows.<String>begin("parent")
                .step("parent-s1", (ctx, in) -> {
                    recordedExecIds.add(ctx.executionId());
                    return in;
                })
                .then(childFlow)
                .build();

        FlowExecution<String> exec = parentFlow.run("init", RunOptions.builder().executionId("my-exec-123").build());
        Assert.assertTrue(exec.result().isSucceeded());
        Assert.assertEquals("my-exec-123", exec.executionId());

        Assert.assertEquals(2, recordedExecIds.size());
        Assert.assertEquals("my-exec-123", recordedExecIds.get(0));
        Assert.assertEquals("my-exec-123", recordedExecIds.get(1));
    }

    @Test
    public void invocationIdUniqueness_twoMountedSubflows_distinctInvocationIds() {
        List<String> recordedInvocationIds = new ArrayList<String>();

        Flow<String, String> child = Flows.<String>begin("reused-child")
                .step("sub-s1", (ctx, in) -> {
                    recordedInvocationIds.add(ctx.invocationId());
                    return in + "-1";
                })
                .step("sub-s2", (ctx, in) -> {
                    recordedInvocationIds.add(ctx.invocationId());
                    return in + "-2";
                })
                .build();

        Flow<String, String> parent = Flows.<String>begin("parent-two-subs")
                .step("p1", (ctx, in) -> {
                    recordedInvocationIds.add(ctx.invocationId());
                    return in;
                })
                .then(child)
                .step("p2", (ctx, in) -> {
                    recordedInvocationIds.add(ctx.invocationId());
                    return in;
                })
                .then(child)
                .step("p3", (ctx, in) -> {
                    recordedInvocationIds.add(ctx.invocationId());
                    return in;
                })
                .build();

        FlowExecution<String> exec = parent.run("test", RunOptions.builder().executionId("exec-dup").build());
        Assert.assertTrue(exec.result().isSucceeded());

        Assert.assertEquals(7, recordedInvocationIds.size());
        Set<String> uniqueIds = new HashSet<String>(recordedInvocationIds);
        Assert.assertEquals(7, uniqueIds.size());

        // First mount of child
        String mount1Step1 = recordedInvocationIds.get(1);
        String mount1Step2 = recordedInvocationIds.get(2);
        // Second mount of child
        String mount2Step1 = recordedInvocationIds.get(4);
        String mount2Step2 = recordedInvocationIds.get(5);

        Assert.assertNotEquals(mount1Step1, mount2Step1);
        Assert.assertNotEquals(mount1Step2, mount2Step2);

        Assert.assertTrue(mount1Step1.startsWith("exec-dup#"));
        Assert.assertTrue(mount2Step1.startsWith("exec-dup#"));
    }

    @Test
    public void invocationIdUniqueness_collidingBranchNodeIds_distinctInvocationIds() {
        List<String> branchAInvocs = new ArrayList<String>();
        List<String> branchBInvocs = new ArrayList<String>();
        List<String> otherwiseInvocs = new ArrayList<String>();

        Flow<String, String> branchA = Flows.<String>begin("branchA")
                .step("calc-step", (ctx, in) -> {
                    branchAInvocs.add(ctx.invocationId());
                    return in + "-A";
                })
                .build();

        Flow<String, String> branchB = Flows.<String>begin("branchB")
                .step("calc-step", (ctx, in) -> {
                    branchBInvocs.add(ctx.invocationId());
                    return in + "-B";
                })
                .build();

        Flow<String, String> otherwise = Flows.<String>begin("otherwise")
                .step("calc-step", (ctx, in) -> {
                    otherwiseInvocs.add(ctx.invocationId());
                    return in + "-OTHER";
                })
                .build();

        Flow<String, String> flow = Flows.<String>begin("choose-collide")
                .choose("select", in -> in)
                .when("A", branchA)
                .when("B", branchB)
                .otherwise(otherwise)
                .end()
                .build();

        // Run A
        flow.run("A", RunOptions.builder().executionId("exec-ch").build());
        // Run B
        flow.run("B", RunOptions.builder().executionId("exec-ch").build());
        // Run Otherwise
        flow.run("C", RunOptions.builder().executionId("exec-ch").build());

        Assert.assertEquals(1, branchAInvocs.size());
        Assert.assertEquals(1, branchBInvocs.size());
        Assert.assertEquals(1, otherwiseInvocs.size());

        String invocA = branchAInvocs.get(0);
        String invocB = branchBInvocs.get(0);
        String invocOther = otherwiseInvocs.get(0);

        Assert.assertNotEquals(invocA, invocB);
        Assert.assertNotEquals(invocA, invocOther);
        Assert.assertNotEquals(invocB, invocOther);

        Assert.assertTrue(invocA.contains("/c:0"));
        Assert.assertTrue(invocB.contains("/c:1"));
        Assert.assertTrue(invocOther.contains("/c:otherwise"));
    }

    @Test
    public void invocationIdUniqueness_integerAndStringBranchKeys_distinctInvocationIds() {
        List<String> intBranchInvocs = new ArrayList<String>();
        List<String> strBranchInvocs = new ArrayList<String>();

        Flow<Object, Object> intBranch = Flows.begin("intBranch")
                .step("leaf-node", (ctx, in) -> {
                    intBranchInvocs.add(ctx.invocationId());
                    return in;
                })
                .build();

        Flow<Object, Object> strBranch = Flows.begin("strBranch")
                .step("leaf-node", (ctx, in) -> {
                    strBranchInvocs.add(ctx.invocationId());
                    return in;
                })
                .build();

        Flow<Object, Object> flow = Flows.begin("choose-int-str")
                .choose("select", in -> in)
                .when(Integer.valueOf(1), intBranch)
                .when("1", strBranch)
                .end()
                .build();

        String commonExecId = "fixed-exec-id";
        flow.run(Integer.valueOf(1), RunOptions.builder().executionId(commonExecId).build());
        flow.run("1", RunOptions.builder().executionId(commonExecId).build());

        Assert.assertEquals(1, intBranchInvocs.size());
        Assert.assertEquals(1, strBranchInvocs.size());

        String intInvoc = intBranchInvocs.get(0);
        String strInvoc = strBranchInvocs.get(0);

        Assert.assertEquals("fixed-exec-id#/s0:select/c:0/s0:leaf-node", intInvoc);
        Assert.assertEquals("fixed-exec-id#/s0:select/c:1/s0:leaf-node", strInvoc);
        Assert.assertNotEquals(intInvoc, strInvoc);
    }

    @Test
    public void deeplyNestedChooseAndSubflow_repeatedChildFlowMounts_qualificationAppliedExactlyOnce() {
        List<String> leafInvocations = new ArrayList<String>();
        List<String> leafNodePaths = new ArrayList<String>();
        List<FlowEvent> events = new ArrayList<FlowEvent>();

        // Reusable leaf flow with a step
        Flow<String, String> leafFlow = Flows.<String>begin("leaf-flow")
                .step("leaf-step", (ctx, in) -> {
                    leafInvocations.add(ctx.invocationId());
                    leafNodePaths.add(ctx.nodePath());
                    return in + "-leaf";
                })
                .build();

        // Branch subflow mounting leafFlow
        Flow<String, String> branchFlow = Flows.<String>begin("branch-flow")
                .step("b-step", in -> in + "-b")
                .then(leafFlow)
                .build();

        // Intermediate subflow mounting choose that routes to branchFlow
        Flow<String, String> subflow = Flows.<String>begin("mid-subflow")
                .step("mid-step", in -> in + "-mid")
                .choose("mid-ch", in -> "GO")
                .when("GO", branchFlow)
                .end()
                .build();

        // Main root flow mounting subflow TWICE (repeated child flow mount), then another choose mounting leafFlow directly
        Flow<String, String> mainFlow = Flows.<String>begin("root-flow")
                .step("root-step", in -> in + "-root")
                .then(subflow) // mount 1
                .then(subflow) // mount 2 (repeated)
                .choose("root-ch", in -> "MATCH")
                .when("MATCH", branchFlow) // branch mounting leafFlow again
                .end()
                .build();

        FlowExecution<String> exec = mainFlow.run("start", RunOptions.builder()
                .executionId("deep-exec")
                .trace(true)
                .observer(events::add)
                .build());

        Assert.assertTrue(exec.result().isSucceeded());
        Assert.assertEquals("start-root-mid-b-leaf-mid-b-leaf-b-leaf", exec.result().value());

        // Leaf step should have executed 3 times
        Assert.assertEquals(3, leafInvocations.size());
        Assert.assertEquals(3, leafNodePaths.size());

        // Verify qualification was applied exactly once at each nesting level
        // Mount 1: /s1:mid-subflow/s1:mid-ch/c:0/s1:leaf-flow/s0:leaf-step
        String invoc1 = leafInvocations.get(0);
        Assert.assertEquals("deep-exec#/s1:mid-subflow/s1:mid-ch/c:0/s1:leaf-flow/s0:leaf-step", invoc1);
        Assert.assertEquals("mid-subflow/mid-ch/leaf-flow/leaf-step", leafNodePaths.get(0));

        // Mount 2: /s2:mid-subflow/s1:mid-ch/c:0/s1:leaf-flow/s0:leaf-step
        String invoc2 = leafInvocations.get(1);
        Assert.assertEquals("deep-exec#/s2:mid-subflow/s1:mid-ch/c:0/s1:leaf-flow/s0:leaf-step", invoc2);
        Assert.assertEquals("mid-subflow/mid-ch/leaf-flow/leaf-step", leafNodePaths.get(1));

        // Root choose mount: /s3:root-ch/c:0/s1:leaf-flow/s0:leaf-step
        String invoc3 = leafInvocations.get(2);
        Assert.assertEquals("deep-exec#/s3:root-ch/c:0/s1:leaf-flow/s0:leaf-step", invoc3);
        Assert.assertEquals("root-ch/leaf-flow/leaf-step", leafNodePaths.get(2));

        // All invocation IDs are distinct
        Set<String> uniqueInvocs = new HashSet<String>(leafInvocations);
        Assert.assertEquals(3, uniqueInvocs.size());

        // Trace check
        FlowTrace trace = exec.trace();
        Assert.assertEquals(4, trace.entries().size()); // root-step, mid-subflow(mount1), mid-subflow(mount2), root-ch
    }

    @Test
    public void nestedObserverAndTracePropagation_receivesAllEventsWithHierarchicalPaths() {
        List<FlowEvent> events = new ArrayList<FlowEvent>();
        FlowObserver observer = events::add;

        Flow<String, String> subflow = Flows.<String>begin("sub")
                .step("s1", in -> in + "-s1")
                .step("s2", in -> in + "-s2")
                .build();

        Flow<String, String> branchFlow = Flows.<String>begin("branchA")
                .step("b1", in -> in + "-b1")
                .build();

        Flow<String, String> mainFlow = Flows.<String>begin("main")
                .step("prep", in -> in + "-prep")
                .then(subflow)
                .choose("ch", in -> "A")
                .when("A", branchFlow)
                .end()
                .step("finish", in -> in + "-done")
                .build();

        FlowExecution<String> exec = mainFlow.run("init", RunOptions.builder()
                .executionId("exec-obs")
                .trace(true)
                .observer(observer)
                .build());

        Assert.assertTrue(exec.result().isSucceeded());
        Assert.assertEquals("init-prep-s1-s2-b1-done", exec.result().value());

        // Verify observer events
        Assert.assertFalse(events.isEmpty());
        Assert.assertEquals(FlowEvent.Type.FLOW_STARTED, events.get(0).type());
        Assert.assertEquals("main", events.get(0).flowId());
        Assert.assertEquals("exec-obs", events.get(0).executionId());

        List<String> nodePathsStarted = new ArrayList<String>();
        for (FlowEvent e : events) {
            if (e.type() == FlowEvent.Type.NODE_STARTED) {
                nodePathsStarted.add(e.nodePath());
            }
        }

        // Expected started paths in order: prep, sub, sub/s1, sub/s2, ch, ch/b1, finish
        Assert.assertTrue(nodePathsStarted.contains("prep"));
        Assert.assertTrue(nodePathsStarted.contains("sub"));
        Assert.assertTrue(nodePathsStarted.contains("sub/s1"));
        Assert.assertTrue(nodePathsStarted.contains("sub/s2"));
        Assert.assertTrue(nodePathsStarted.contains("ch"));
        Assert.assertTrue(nodePathsStarted.contains("ch/b1"));
        Assert.assertTrue(nodePathsStarted.contains("finish"));

        // Verify trace hierarchy
        List<FlowTrace.Entry> rootEntries = exec.trace().entries();
        Assert.assertEquals(4, rootEntries.size());
        Assert.assertEquals("prep", rootEntries.get(0).nodeId());
        Assert.assertEquals("sub", rootEntries.get(1).nodeId());
        Assert.assertEquals(NodeKind.SUBFLOW, rootEntries.get(1).kind());
        Assert.assertEquals("ch", rootEntries.get(2).nodeId());
        Assert.assertEquals(NodeKind.CHOOSE, rootEntries.get(2).kind());
        Assert.assertEquals("finish", rootEntries.get(3).nodeId());

        // Subflow trace children
        List<FlowTrace.Entry> subChildren = rootEntries.get(1).children();
        Assert.assertEquals(2, subChildren.size());
        Assert.assertEquals("s1", subChildren.get(0).nodeId());
        Assert.assertEquals("sub/s1", subChildren.get(0).nodePath());
        Assert.assertEquals("s2", subChildren.get(1).nodeId());
        Assert.assertEquals("sub/s2", subChildren.get(1).nodePath());

        // Choose trace children
        List<FlowTrace.Entry> chooseChildren = rootEntries.get(2).children();
        Assert.assertEquals(1, chooseChildren.size());
        Assert.assertEquals("b1", chooseChildren.get(0).nodeId());
        Assert.assertEquals("ch/b1", chooseChildren.get(0).nodePath());
    }

    @Test
    public void observerError_propagatedAndNotSwallowed() {
        AssertionError expectedError = new AssertionError("Observer critical assertion failed");
        FlowObserver errorObserver = event -> {
            throw expectedError;
        };

        Flow<String, String> flow = Flows.<String>begin("obs-error-flow")
                .step("step1", in -> in)
                .build();

        try {
            flow.run("test", RunOptions.builder().observer(errorObserver).build());
            Assert.fail("Expected AssertionError to propagate");
        } catch (AssertionError e) {
            Assert.assertSame(expectedError, e);
        }

        try {
            flow.call("test");
        } catch (Exception e) {
            Assert.fail("call() without observer should not fail");
        }
    }

    @Test
    public void observerRuntimeException_isolatedAndFlowSucceeds() {
        AtomicBoolean ran = new AtomicBoolean();
        FlowObserver brokenObserver = event -> {
            ran.set(true);
            throw new IllegalStateException("Observer failure");
        };

        Flow<String, String> flow = Flows.<String>begin("obs-runtime-flow")
                .step("step1", in -> in + "-ok")
                .build();

        FlowExecution<String> exec = flow.run("test", RunOptions.builder().observer(brokenObserver).build());
        Assert.assertTrue(exec.result().isSucceeded());
        Assert.assertEquals("test-ok", exec.result().value());
        Assert.assertTrue(ran.get());
    }

    @Test
    public void recoveredInterruptedException_retainsInterruptFlag() {
        Thread.interrupted(); // clear interrupt status before test

        Flow<String, String> flow = Flows.<String>begin("interrupt-recover")
                .step("sleep-step", (Step<String, String>) in -> {
                    throw new InterruptedException("Thread interrupted during sleep");
                })
                .recover("rec", (in, failure) -> FlowResult.succeeded("recovered:" + in))
                .build();

        try {
            FlowExecution<String> exec = flow.run("val");
            Assert.assertTrue(exec.result().isSucceeded());
            Assert.assertEquals("recovered:val", exec.result().value());
            Assert.assertTrue("Thread interrupt flag must be retained after recovering InterruptedException",
                    Thread.currentThread().isInterrupted());
        } finally {
            Thread.interrupted(); // cleanup
        }
    }

    @Test
    public void recoverRethrowOriginalFailure_retainsOriginalNodeAndCause_noSelfSuppression() {
        CustomTestException originalEx = new CustomTestException("Original DB failure");

        Flow<String, String> flow = Flows.<String>begin("rec-rethrow")
                .step("db-step", (Step<String, String>) in -> {
                    throw originalEx;
                })
                .recover("rec-handler", (in, failure) -> {
                    // Rethrow original exception
                    throw (RuntimeException) failure.cause();
                })
                .build();

        FlowExecution<String> exec = flow.run("input");
        Assert.assertTrue(exec.result().isFailed());
        Assert.assertEquals("db-step", exec.result().failure().nodeId());
        Assert.assertSame(originalEx, exec.result().failure().cause());
        Assert.assertEquals(0, originalEx.getSuppressed().length);
    }

    @Test
    public void ensureRethrowOriginalFailure_retainsOriginalNodeAndCause_noSelfSuppression() {
        CustomTestException originalEx = new CustomTestException("Network timeout");

        Flow<String, String> flow = Flows.<String>begin("ensure-rethrow")
                .step("http-step", (Step<String, String>) in -> {
                    throw originalEx;
                })
                .ensure("ensure-handler", (in, completion) -> {
                    if (completion.isFailed()) {
                        throw (RuntimeException) completion.failure().cause();
                    }
                })
                .build();

        FlowExecution<String> exec = flow.run("input");
        Assert.assertTrue(exec.result().isFailed());
        Assert.assertEquals("http-step", exec.result().failure().nodeId());
        Assert.assertSame(originalEx, exec.result().failure().cause());
        Assert.assertEquals(0, originalEx.getSuppressed().length);
    }

    @Test
    public void ensureNewException_attachedToSuppressed_whenAlreadyFailed() {
        CustomTestException originalEx = new CustomTestException("Original error");
        RuntimeException ensureEx = new RuntimeException("Ensure cleanup error");

        Flow<String, String> flow = Flows.<String>begin("ensure-suppress")
                .step("step-err", (Step<String, String>) in -> {
                    throw originalEx;
                })
                .ensure("ensure-handler", (in, completion) -> {
                    throw ensureEx;
                })
                .build();

        FlowExecution<String> exec = flow.run("input");
        Assert.assertTrue(exec.result().isFailed());
        Assert.assertEquals("step-err", exec.result().failure().nodeId());
        Assert.assertSame(originalEx, exec.result().failure().cause());
        Assert.assertEquals(1, originalEx.getSuppressed().length);
        Assert.assertSame(ensureEx, originalEx.getSuppressed()[0]);
    }
}
